[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.52.2",
    "fastapi[standard]>=0.115.12",
    "logger>=1.4",
    "mcp>=1.9.2",
    "requests>=2.32.3",
    "utils>=1.0.2",
]
